example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
# TODO: Implement Routings Here
from django.urls import path
from mywatchlist.views import show_mywatchlist, show_mywatchlist_html, show_mywatchlist_json, show_mywatchlist_xml

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist_html, name='show_mywatchlist_html'),
    path('xml/', show_mywatchlist_xml, name='show_mywatchlist_xml'),
    path('json/', show_mywatchlist_json, name='show_mywatchlist_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
    path("__reload__/", include("django_browser_reload.urls")),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *

app_name = 'todolist'

urlpatterns = [
    path('', show_todo, name='show_todo'),
    path('register/', register, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login/', login_user, name='login'),
    path('create-task/', create_task, name='create-task'),
    path('delete/<int:pk>', delete, name='delete'),
    path('change/<int:pk>', change, name='change'),
    path('json/', show_json, name='show_json'),
    path('add/', add_ajax, name='add_ajax'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class MyWatchlistItem(models.Model):
    watched_movie = models.BooleanField()
    movie_name = models.CharField(max_length=255)
    movie_rating = models.IntegerField()
    movie_date = models.DateField()
    movie_review = models.CharField(max_length=255)

todolist/models.py
from statistics import mode
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    status = models.BooleanField(null=True, blank=True)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.

def show_katalog(request):
    return render(request, "katalog.html", context)

data_katalog = CatalogItem.objects.all()
context = {
    'list_barang': data_katalog,
    'nama': 'Yudi Putra Sabri',
    'npm': 2106706123,
}

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import MyWatchlistItem
from django.http import HttpResponse
from django.core import serializers
# TODO: Create your views here.
data = MyWatchlistItem.objects.all()
def show_mywatchlist(request):
    result = ""
    watched = 0
    unwatched = 0

    for a in data:
        if (a.watched_movie): watched += 1
        else: unwatched += 1

    if watched > unwatched : result = "Selamat, kamu sudah banyak menonton!"
    elif watched == unwatched : result = "Waduh, Kamu menonton setengah dari list kamu. Ayo tambah lagi!"
    else : result = "Wah, kamu masih sedikit menonton!"    

    context = {
    'nama': 'Yudi Putra Sabri',
    'npm': 2106706123,
    'result' :result,
    'watched' : watched,
    'unwatched' : unwatched,
    }

    return render(request, "main.html", context)


context = {
    'list_movie': data,
    'nama': 'Yudi Putra Sabri',
    'npm': 2106706123,
}

def show_mywatchlist_html(request):
    return render(request, "mywatchlist.html", context)

def show_mywatchlist_xml(request):
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
    
def show_mywatchlist_json(request):
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
from django.shortcuts import render
import datetime
from todolist.models import Task
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.core import serializers
from django.http.response import JsonResponse, HttpResponse

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todo(request):
    data = Task.objects.filter(user=request.user)
    context = {
    'list_todo' : data,
    'username' :  request.user.username,
    }

    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todo")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('todo')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        status = False
        Task.objects.create(title=title, description=description, date=date, user=user, status=status)
        response = HttpResponseRedirect(reverse("todolist:show_todo")) 
        return response

    return render(request, "add.html")

@csrf_exempt    
def delete(request, pk):
    if request.method == 'DELETE':
        Task.objects.filter(id=pk).delete()
    return JsonResponse({"instance": "Proyek Dihapus"},status=200)

def change(request, pk):
    data = Task.objects.get(id=pk)
    data.status = not(data.status)
    data.save()
    return redirect('todolist:show_todo')

@login_required(login_url='/todolist/login/')
def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', task), content_type='application/json')

@login_required(login_url='/todolist/login/')
def add_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('nama')
        description = request.POST.get('desc')
        date = datetime.datetime.now()
        user = request.user
        status = False
        item = Task(title=title, description=description, date=date, user=user, status=status)
        item.save()
        return JsonResponse({"instance": "Proyek Dibuat"},status=200)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table border="1">
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
    <tr>
        <th>{{barang.item_name}}</th>
        <th>{{barang.item_price}}</th>
        <th>{{barang.item_stock}}</th>
        <th>{{barang.rating}}</th>
        <th>{{barang.description}}</th>
        <th>{{barang.item_url}}</th>
    </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/main.html
{% extends 'base.html' %}

{% load static %}
<!-- CSS CUSTOM -->
<link rel="stylesheet" href="{% static 'main.css' %}">

{% block content %}

 <h1>Tugas 3 PBP</h1>

 <h5>Name: </h5>
 <p>{{nama}}</p>

 <h5>Student ID: </h5>
 <p>{{npm}}</p>


 <div class="main-container">
   <div class="inside-border">
      <h2>Here are My Works for Assignment 3</h2>
      <div class="works">
         <h1 class="link">Hit the Buttons :D</h1>
         <button onclick="location.href='/mywatchlist/html'">HTML</button>
         <button onclick="location.href='/mywatchlist/xml'">XML</button>
         <button onclick="location.href='/mywatchlist/json'">JSON</button>
      </div>
   </div>
 </div>
 <div class="result">
   <p class="final"> {{result}}</p>
   <p class="result-description">Kamu menonton {{watched}} film dan belum menonton {{unwatched}} film dari list kamu</p>
 </div>



{% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Tugas 3 PBP</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>

  <table border="1">
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
    {% for movie in list_movie %}
        <tr>
            <th>{{movie.watched_movie}}</th>
            <th>{{movie.movie_name}}</th>
            <th>{{movie.movie_rating}}</th>
            <th>{{movie.movie_date}}</th>
            <th>{{movie.movie_review}}</th>
        </tr>
    {% endfor %}
  </table>

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'main.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>

todolist/templates/add.html
{% extends 'base.html' %}

{% block meta %}
<title>Create New Todo List</title>
{% endblock meta %}

{% block content %}
{% load static tailwind_tags %}
{% tailwind_css %}
<div class="bg-slate-100 h-screen p-8 flex flex-col">
    <div class=" bg-slate-500 p-6 rounded-2xl flex justify-center items-center">
        <h1 class="font-bold text-3xl text-white">Create Todo List</h1>
    </div>
    
    <div class="flex justify-center m-20">
        <div class=" bg-slate-900 bg-opacity-40 rounded-3xl w-fit p-8 ">  
            <form method="POST" action="">
                {% csrf_token %}
                <div class="">
                    <table>
                        <tr>
                            <td>Todo:</td>
                            <td><input class="rounded-2xl" type="text" name="todo" placeholder="What's New?" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <div class="flex gap-4">
                                <td>Description: </td>
                                <td><input class="rounded-2xl" type="text" name="description" placeholder="Description" class="form-control"></td>
                            </div>

                        </tr>
                    </table>
                </div>
                
                <div class="flex gap-4 mt-4 justify-center">
                    <div class="p-3 rounded-2xl w-fit cursor-pointer bg-orange-400 flex items-center">
                        <input class=" text-white text-lg font-bold" type="submit" name="submit" value="Create!"/>
                    </div>
                    <div class="p-3 rounded-2xl w-fit cursor-pointer bg-gray-900">
                        <button class="p-1 text-white font-bold text-lg"><a href="../">Back</a></button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

todolist/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  </head>
  <body>
    {% load static tailwind_tags %}
    {% tailwind_css %}
    <div class=" bg-slate-200">
        <div class ="h-screen flex items-center justify-center shadow-2xl">
            <div class="">
                <div class="rounded-4 bg-secondary p-5 mt">

                    <div class=" bg-orange-300 p-3 rounded-2xl w-full m-2 flex justify-center">
                        <h1 class="font-bold text-white">Login First!</h1>
                    </div>

                    <form method="POST" action="">
                        {% csrf_token %}
                        <table>
                            <tr>
                                <div class="p-2 w-full justify-center flex ">
                                    <input class="rounded-2xl p-2 flex justify-center" type="text" name="username" placeholder="Username" class="form-control">
                                </div>
                            </tr>    
                            <tr>
                                <p></p>
                                <div class="p-2 w-full justify-center flex ">
                                    <input class="rounded-2xl p-2" type="password" name="password" placeholder="Password" class="form-control">
                                </div>
                            </tr>

                            {% if messages %}
                            {% for message in messages %}
                            <div class=" m-2 rounded-lg">
                                <p class="">Note : {{ message }}</p>
                            </div>
                            {% endfor %}
                            {% endif %} 
                
                            <tr>
                                <div class=" bg-green-500 rounded-2xl m-2 p-2 w-full justify-center flex cursor-pointer">
                                    <input class="cursor-pointer text-white font-bold font-monospace" type="submit" value="Login">
                                </div>
                            </tr>
                        </table>
                    </form>
                
                    <div class="flex justify-center bg-red-500 p-2 m-2 rounded-full w-full items-center gap-2">
                        <p class="text-white">Belum mempunyai akun? 
                        <div class="bg-white p-1 rounded-full cursor-pointer">
                            <a class="font-bold" href="{% url 'todolist:register' %}">Buat Akun</a>
                        </div>
                    </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

todolist/templates/register.html
{% extends 'base.html' %}
{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}  
{% load static tailwind_tags %}
{% tailwind_css %}
<div class = "login bg-zinc-50 h-screen">
    <div class="flex justify-center p-8 m-8 rounded-2xl bg-zinc-700">
        <p class="text-white font-bold text-2xl">Registration Form</p>  
    </div>

    <div class="flex justify-center items-center">
        <div class=" h-fit bg-slate-700 bg-opacity-10 p-5 rounded-2xl">
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td>
                            <div class="flex gap-5 mt-4">
                                <div class=" bg-green-500 p-3 rounded-2xl w-fit cursor-pointer flex items-center">
                                    <input class="text-white font-bold text-lg cursor-pointer" type="submit" name="submit" value="Daftar"/>
                                </div>
                                <div class="p-3 rounded-2xl w-fit cursor-pointer bg-gray-900">
                                    <button class="p-1 text-white font-bold text-lg"><a href="{% url 'todolist:logout' %}">Back to Login</a></button>
                                </div>
                            </div>
                        </td>  
                    </tr>  
                </table>  
            </form>
        </div>
    </div>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% load static tailwind_tags %}
{% tailwind_css %}

<!-- Source Modal Tailwinds : https://hartdev-ctzyoepto-hudadamar21.vercel.app/source-code/tailwindcss-components/modal-with-animation/ -->
<title>ToDo List</title>
<div class=" bg-gray-300 min-h-screen w-fit">
  <div class=" bg-orange-300 h-16 w-screen">
    <div class="flex items-center h-16 p-8">
      <p class=" font-bold text-black">Hello {{username}}</p>

      <div class="p-3">
        <div class="flex gap-5">
          <button onclick="openModal(true)" class="bg-green-500 hover:bg-green-600 px-4 py-2 rounded text-white focus:outline-none">
            Add New Task!
          </button>
          <div class=" bg-red-600 hover:bg-red-700 p-1 w-fit rounded-2xl">
            <button class="p-1 text-white font-bold"><a href="{% url 'todolist:logout' %}">Logout</a></button>
          </div>
        </div>
      </div>
      <!-- overlay -->
      <div id="modal_overlay" class="hidden absolute inset-0 bg-black bg-opacity-30 h-full w-screen flex justify-center items-center pt-10 md:pt-0">
        <!-- modal -->
        <div id="modal" class="opacity-0 transform -translate-y-full scale-150 relative h-fit bg-white w-10/12 rounded shadow-lg transition-opacity transition-transform duration-300">
          <!-- button close -->
          <button 
          onclick="openModal(false)"
            class="absolute -top-3 -right-3 bg-red-500 hover:bg-red-600 text-2xl w-10 h-10 rounded-full focus:outline-none text-white">
            &cross;
          </button>
          <!-- body -->
          <div class="w-full p-3">
            <div class="bg-slate-100 h-full p-4 flex flex-col">
              <div class=" bg-slate-500 p-6 rounded-2xl flex justify-center items-center">
                  <h1 class="font-bold text-3xl text-white">Create Todo List</h1>
              </div>
              
              <div class="flex justify-center m-20">
                  <div class=" bg-slate-900 bg-opacity-40 rounded-3xl w-fit p-8 ">  
                      <form method="POST" action="" id="tembak_db">
                          {% csrf_token %}
                          <div class="">
                              <table>
                                  <tr>
                                      <td>Todo:</td>
                                      <td><input class="rounded-2xl" type="text" name="todo" placeholder="What's New?" class="form-control" id="nama"></td>
                                  </tr>
                                          
                                  <tr>
                                      <div class="flex gap-4">
                                          <td>Description: </td>
                                          <td><input class="rounded-2xl" type="text" name="description" placeholder="Description" class="form-control" id="desc"></td>
                                      </div>
          
                                  </tr>
                              </table>
                          </div>
                          
                          <div class="flex gap-4 mt-4 justify-center">
                              <div class="p-3 rounded-2xl w-fit cursor-pointer bg-orange-400 flex items-center">
                                  <input class=" text-white text-lg font-bold" type="submit" name="submit" value="Create!"/>
                              </div>
                          </div>
                      </form>
                  </div>
              </div>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="flex  justify-center justify-items-center bg-gray-300 h-fit mt-4 p-4">
    <div class="grid lg:grid-cols-4 md:grid-cols-3 gap-5 mt-8 sm:mt-5" id="todoCard">
      
    </div>
  </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  const modal_overlay = document.querySelector('#modal_overlay');
  const modal = document.querySelector('#modal');
  const nama = document.getElementById('nama');
  const desc = document.getElementById('desc');

  
  function openModal (value){
    const modalCl = modal.classList
    const overlayCl = modal_overlay
    if(value){
      overlayCl.classList.remove('hidden')
      setTimeout(() => {
        modalCl.remove('opacity-0')
        modalCl.remove('-translate-y-full')
        modalCl.remove('scale-150')
        nama.value = '';
        desc.value = '';
      }, 100);
    } else {
      modalCl.add('-translate-y-full')
      setTimeout(() => {
        modalCl.add('opacity-0')
        modalCl.add('scale-150')
      }, 100);
      setTimeout(() => overlayCl.classList.add('hidden'), 300);
    }
  } 
  
  $(document).ready(function () {
    loadData();
  });


  function delDB(val){
    $.ajax({
      type :"DELETE",
      csrfmiddlewaretoken: "{{ csrf_token }}",
      url :`/todolist/delete/${val}`,
      success: function () {
        $(`#${val}`).remove()
      },
    })
  }

  $(document).on("submit", "#tembak_db", function (e) {
    e.preventDefault();
    $.ajax({
      type: "POST",
      url: "{% url 'todolist:add_ajax' %}",
      data: {
        nama: $("#nama").val(),
        desc: $("#desc").val(),
        csrfmiddlewaretoken: "{{ csrf_token }}",
      },
      dataType: "json",
      success: function () {
        openModal(false)
        loadData();
      },
    });
  });

  function loadData() {
    let tab= "";
    $.ajax({
        url: "{% url 'todolist:show_json' %}",
        type: "GET",
        dataType: "json",
        success: function(resp){  
            for (let i of resp){
                let status = i.fields.status ? "Finished" : "Not Yet";
                tab +=`
                <div id="${i.pk}" class="bg-white rounded-2xl p-8 flex flex-col gap-2 hover:drop-shadow-2xl transition duration-300 ease-in-out">
                  <p class="text-center text-xl font-semibold">${i.fields.title}</p>
                  <p class="text-center text-xs">${i.fields.date}</p>
                  <div class="flex m-2 p-2 flex-col">
                    <div class="transition-opacity bg-gray-600 bg-opacity-10 rounded-2xl p-2">
                      <p class="break-all">${i.fields.description}</p>
                      <p>
                        ${status}
                      </p>
                    </div>
                  </div>
                  <div class="w-full flex justify-center gap-2">
                    <a href="change/${i.pk}"><button class=" bg-red-600 rounded-2xl p-2 text-white font-bold">Change Status</button></a>
                    <button class="bg-green-500 rounded-2xl p-2 text-white font-bold delete" onclick="delDB(${i.pk})">Delete</button>
                  </div>
                </div>`
              ;
              $('#todoCard').html(tab);
            }
        },
        error: function(resp){
            console.log('Error?');
        }
    })
  };

</script>